__1074 Z__

```python
import sys
input = sys.stdin.readline

def zett(y, x, num):
    global cnt
    if num == 1:
        if y == r and x == c:
            print(cnt)
            return
        else:
            cnt += 1
            return
    if y<=r<y+num//2 and x<=c<x+num//2:
        zett(y, x, num//2)
        return
    elif y<=r<y+num//2 and x+num//2<=c<x+num:
        cnt += (num**2)//4
        zett(y, x+num//2, num//2)
        return
    elif y+num//2<=r<y+num and x<=c<x+num//2:
        cnt += (num**2)//2
        zett(y+num//2, x, num//2)
        return
    elif y+num//2<=r<y+num and x+num//2<=c<x+num:
        cnt += (num**2)//4*3
        zett(y+num//2, x+num//2, num//2)
        return

N, r, c = map(int, input().split())
n = 2**N
cnt = 0
zett(0, 0, n)
```

1. 처음에 자꾸 메모리 초과가 나서 뭐가 잘못됐나 봤더니 쓰지도 않는 배열을 구현하고 있었다.

```python
maps = [[0] * n for _ in range(n)]
```

​	이런 식으로 낭비된 메모리가 있어서 지워주고 다시 제출했다. 그런데 시간초과가 나왔다.

2. 구선생님의 힘을 빌려서 힌트만 살짝 얻기로 했다. 범위 내 존재하지 않으면 굳이 recursion을 해줄 필요가 없음을 알게됐다. 그래서 선순위인 경우 cnt에 + 해주고 아닌 경우에는 재귀호출을 하지 않았다.

3. 이후에 코드를 구현했고, TC도 전부 맞음을 확인했다. 그런데 자꾸 1%에서 틀렸다고 나왔다.

   - 반례를 찾기 위해 간단하게 N=2를 두고 모든 경우의 수를 대입해봤다. 그러자 2 1 2와 2 3 2가 답이 도출이 되지 않았다.

   - 역시 범위 설정 문제였다.. 하나하나 수기로 입력하다보니까 3번째 조건을 잘못 적었다.

   - ```python
     x <= c < num // 2 # 이렇게 써놨었다
     x <= c < x+(num//2) # 이게 맞는 코드
     ```